spring:
  profiles.active: runtime
  
SOHEBOX_ROOT: C:/Hien/svn_checkout/Sohebox

MYSQL_HOST_SCHEMA: localhost:3306/sohebox_test
MYSQL_USERNAME: admin
MYSQL_PASSWORD: admin

AUTHEN_ENABLE: true
JWT_SECRET: xxxxxx

SQL_LOG_LEVEL: INFO