spring:
  profiles.active: runtime
  
SOHEBOX_ROOT: C:/Hien/svn_checkout/Sohebox

MYSQL_HOST_SCHEMA:localhost:3306/sohebox_test
MYSQL_USERNAME: xxxxxx
MYSQL_PASSWORD: xxxxxx

MAIL_USERNAME: xxxxxx
MAIL_PASSWORD: xxxxxx

AUTHEN_ENABLE: true
JWT_SECRET: xxxxxx

SSL_ENABLE: true
CERT_PASSWORD: xxxxxx